<div class="col-md-8">
	
<h2>New Topics</h2>
<form action="" method="POST" class="form-horizontal">
	
    <div class="form-group">
        <label id="title">Title :</label>
        <input type="text" name="title" class="form-control">
    </div>

    <div class="form-group">
    	<label id="description">Description :</label>
    	<textarea name="description" class="form-control input-lg"></textarea>
    </div>
    <div class="form-group">
		<button type="submit" class="btn btn-primary">Add Topic</button>
    </div>
</form>

</div>
