<?php  
$topic = $this->topic;
?>
<div class="col-md-8">
	

<h2>Edit Topics</h2>
<form action="<?=$_SERVER['PATH_INFO'];?>" method="POST" class="form-horizontal">

<input type="hidden" name="id" value="<?=$topic['id'];?>">

 <div class="form-group">	
	<label id="title">Title :</label>
		<input type="text" name="title" value="<?=$topic['title'];?>" class="form-control">
 </div>

 <div class="form-group"> 	
	<label>Description :</label>
		<textarea name="description" cols="50" rows="20" class="form-control"><?=$topic['description'];?></textarea>
 </div>

 <div class="form-group">
	<button type="submit" class="btn btn-primary">Edit Topic</button>
 </div>
</form>

</div>