	<?php
	$topics = $this->topics;
	// print_r($topics);
	
	foreach ($topics as $topic) {
		?>
		<section>

			<div class="row">
				<div class="col-xs-12">
					<h3><?=$topic['title'];?></h3>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-8">
					<p class="text-muted">
						<?=nl2br($topic['description']);?>
					</p>
				</div>

				<div class="col-xs-4">
					<p class="pull-right">
	<a href="/vote/add/<?=$topic['id']; ?>" class="btn btn-success">
	    <span class="glyphicon glyphicon-thumbs-up">
	        <strong><?=(isset($topic['count'])) ? $topic['count'] : 0;?></strong>
	    </span>
	</a>
	<a href="edit/<?=$topic['id'];?>" class="btn btn-primary">Edit</a>
	<button onclick="deletePhoto(<?=$topic['id'];?>);" class="btn btn-danger">Delete</button>
					</p>
				</div>
			</div>

		</section>
		<hr>
		<?php
			}
			?>